-- This file is no longer the source of truth for the database schema.
-- The full schema is created automatically by server/db.js initDb() on startup.
-- See db.js for the authoritative table definitions.
